-- Load-time script (mod.json postRunScript). Prepares every rail vehicle (locos,
-- coaches and wagons) the game knows about, INCLUDING modded ones, so that the run-around ghost can be drawn
-- from the loco's OWN model with its own sound, smoke, wheels and paint.
--
-- A free entity has no vehicle data, and the game's sound and transformator scripts
-- for locos read vehicle data (the stock sound script dies with "attempt to index
-- local 'vehicleInfo'"). So for each loco:
--
--  * its transformator, when it is the stock train one (default_train.trf), is
--    pointed at res/models/runaround_ghost/real.trf, whose script
--    (res/scripts/ghost_real.script.lua) does exactly what the stock one does for a
--    real train and drives wheels, smoke and paint from the ghost's state for a
--    free entity;
--  * its sound set, when it is one of the game's own, is pointed at the matching
--    copy in res/audio/ghostwrap/: the same sound set with its update script
--    wrapped the same way. (The game refuses sound sets added or changed at run
--    time - soundSetRep.addAsTable / setAsTable throw std::exception - so these
--    copies are shipped as files, generated from the game's own.)
--
-- A loco for which both went through is marked with a marker model,
-- "runaround_ghost_real/<file>.mdl", which the run-around script looks for (a game
-- script cannot read model metadata). For every loco a ghost COPY is also built,
-- "runaround_ghost_dyn/<file>.mdl" (its meshes, particles, the wrapped sound set if
-- there is one, and the wrapped transformator), used when the loco's own model
-- cannot be: e.g. a modded loco with its own sound set or transformator script.
--
-- Markers and copies are named by the model's FILE name, because that is what is
-- known to match between here and the game script (the run-around looks them up
-- by the file name of a train's loco, which works live; whether full model names
-- read the same in both places has not been shown). So a file name that two or
-- more rail vehicles share (two mods' "loco.mdl", say) would be ambiguous: those
-- vehicles are left exactly as they are, with no marker and no copy, and the
-- run-around gives them the generic ghost (and coaches stay in view).
--
-- Everything is wrapped in pcall: a loco the game will not let us change is left
-- exactly as it was.

local mod = {}

-- This mod's ID, as in mod.json. The wrapped transformators and sound sets
-- (res/models/runaround_ghost/*.trf.lua, res/audio/ghostwrap/*.snd.lua) name
-- res/scripts/ghost_real.script with it, the way the game's own DLC names its
-- files: they are plain data files and cannot look the ID up. If the game loads
-- the mod under another ID, nothing is patched (see postRunFn).
local MOD_ID = "runaround_helper_1"
-- false = leave the game's locos untouched (then only the ghost copies are used)
local PATCH_LOCOS = true
-- A vehicle whose transformator is not the game's own (another mod's, e.g. the
-- "devers" track-cant mod gives every train its own) is pointed at
-- res/models/runaround_ghost/chain.trf, with the original's name in
-- transformatorConfig.params.runaround_trf (other params kept): ghost_real's
-- chain function hides it or drives its ghost, and otherwise calls the original.
-- false = leave such vehicles alone (they then run around as plain copies).
local CHAIN_TRANSFORMATORS = true

-- The game's own sound sets that have a wrapped copy in res/audio/ghostwrap/
-- (generated by the mod's author from the game files; see that folder).
local WRAPPED_SOUND_SETS = {
	["/vehicle/train/shared/sound/cabcar_modern.snd"] = "cabcar_modern",
	["/vehicle/train/shared/sound/train_diesel.snd"] = "train_diesel",
	["/vehicle/train/shared/sound/train_diesel_electric.snd"] = "train_diesel_electric",
	["/vehicle/train/shared/sound/train_diesel_hydraulic.snd"] = "train_diesel_hydraulic",
	["/vehicle/train/shared/sound/train_diesel_old.snd"] = "train_diesel_old",
	["/vehicle/train/shared/sound/train_electric_medium.snd"] = "train_electric_medium",
	["/vehicle/train/shared/sound/train_electric_modern.snd"] = "train_electric_modern",
	["/vehicle/train/shared/sound/train_electric_old.snd"] = "train_electric_old",
	["/vehicle/train/shared/sound/train_steam_modern.snd"] = "train_steam_modern",
	["/vehicle/train/shared/sound/train_steam_old.snd"] = "train_steam_old",
	["/vehicle/waggon/shared/sound/waggon_freight_modern.snd"] = "waggon_freight_modern",
	["/vehicle/waggon/shared/sound/waggon_freight_old.snd"] = "waggon_freight_old",
	["/vehicle/waggon/shared/sound/waggon_modern.snd"] = "waggon_modern",
	["/vehicle/waggon/shared/sound/waggon_old.snd"] = "waggon_old",
	["/vehicle/train/handcar/sound/handcar.snd"] = "handcar",
}

local function log(...)
	local parts = {}
	for i = 1, select("#", ...) do parts[i] = tostring(select(i, ...)) end
	print("[RunAroundHelper] " .. table.concat(parts, " "))
end

local function clone(v)
	if type(v) ~= "table" then return v end
	local o = {}
	for k, x in pairs(v) do o[k] = clone(x) end
	return o
end

-- Any rail vehicle: locos, and (for the ghost rake) coaches and wagons.
local function isRailVehicle(meta)
	local tv = meta and meta.transportVehicle
	return tv ~= nil and tv.carrier == "RAIL" and meta.landVehicle ~= nil
end

-- The wrapped copy of a sound set, as a resource name, or nil if there is none.
local function wrappedSoundSet(soundSetName)
	if type(soundSetName) ~= "string" then return nil end
	local key = soundSetName
	if string.sub(key, 1, 3) == "::/" then key = string.sub(key, 3) end
	local file = WRAPPED_SOUND_SETS[key]
	return file and (MOD_ID .. "::/res/audio/ghostwrap/" .. file .. ".snd") or nil
end

-- The game's stock train transformators and their wrapped versions.
local WRAPPED_TRANSFORMATORS = {
	["default_train.trf"] = "real.trf",
	["tilting_train.trf"] = "real_tilting.trf",
}

-- The wrapped version of a loco's transformator, as a resource name, or nil.
local function wrappedTransformator(meta)
	local name = meta.transformatorConfig and meta.transformatorConfig.transformator and meta.transformatorConfig.transformator.name
	if type(name) ~= "string" then return nil end
	local file = WRAPPED_TRANSFORMATORS[string.match(name, "([^/]+)$") or ""]
	if file == nil or not string.find(name, "vehicle/train/shared/", 1, true) then return nil end
	return MOD_ID .. "::/res/models/runaround_ghost/" .. file
end

-- Whether another transformator can be chained, checked here by loading it the
-- way ghost_real's chain functions will at run time (the same rules: keep the two
-- in step; dev/tests check they agree). Only one that declares nothing but an
-- update and a particle script, and optionally the two extra-model hooks (as
-- mcs_basisset's and the game's hot-air balloon declare), and whose every declared
-- function is found, is chained: chain.trf passes on the first two, chain_emit.trf
-- all four. A transformator with any other hook would lose it, and one whose
-- functions can't be found would lose them. Anything else is left alone, as before
-- chaining existed.
local CHAINABLE_HOOKS = {
	updateScript = true, updateParticleSystemScript = true,
	getEmittableModelsScript = true, computeEmittedModelsScript = true,
}
local EMIT_HOOKS = { "getEmittableModelsScript", "computeEmittedModelsScript" }

local function ownerOf(res)
	return string.match(res, "^([%w_%-%.]*::)") or "::"
end

local function folderOf(res)
	local path = string.gsub(res, "^[%w_%-%.]*::", "")
	return string.match(path, "^(.*/)") or "/"
end

-- Runs a resource file and returns what it defines (its returned table, or the
-- result of the data() it defines); this script's own data() is put back.
local loaded = {}
local function loadResource(file)
	if loaded[file] ~= nil then return loaded[file] or nil end
	local saved = data
	local ok, ret = pcall(ug_require, file)
	local defined = data
	data = saved
	local result = nil
	if ok and type(ret) == "table" then
		result = ret
	elseif ok and type(defined) == "function" and defined ~= saved then
		local okD, d = pcall(defined)
		if okD and type(d) == "table" then result = d end
	end
	loaded[file] = result or false
	return result
end

local function trfFiles(name, modelName)
	local list
	if string.find(name, "::", 1, true) then
		list = { name }
	elseif string.sub(name, 1, 1) == "/" then
		list = { ownerOf(modelName) .. name, "::" .. name }
	else
		list = { ownerOf(modelName) .. folderOf(modelName) .. name }
	end
	for i, f in ipairs(list) do
		if not string.find(f, "%.lua$") then list[i] = f .. ".lua" end
	end
	return list
end

local function scriptFunction(ref, trfFile)
	if type(ref) ~= "string" then return nil end
	local file, path = string.match(ref, "^(.-)@(.+)$")
	if file == nil then return nil end
	local bases
	if string.find(file, "::", 1, true) then
		bases = { file }
	elseif string.sub(file, 1, 1) == "/" then
		bases = { ownerOf(trfFile) .. file, "::" .. file }
	else
		bases = { ownerOf(trfFile) .. folderOf(trfFile) .. file }
	end
	for _, base in ipairs(bases) do
		for _, ext in ipairs({ ".lua", ".tl" }) do
			local t = loadResource(base .. ext)
			if type(t) == "table" then
				local fn = t
				for key in string.gmatch(path, "[^%.]+") do fn = type(fn) == "table" and fn[key] or nil end
				if type(fn) == "function" then return fn end
			end
		end
	end
	return nil
end

-- true and whether it has the extra-model hooks, or false and why, per
-- transformator name (many vehicles share one).
local chainChecks = {}
local function chainable(name, modelName)
	local c = chainChecks[name]
	if c == nil then
		local why, emit = nil, false
		if type(ug_require) ~= "function" then
			why = "can't load other scripts here"
		else
			local cfg, file = nil, nil
			for _, f in ipairs(trfFiles(name, modelName)) do
				cfg = loadResource(f)
				if type(cfg) == "table" then file = f break end
			end
			if type(cfg) ~= "table" or type(cfg.updateScript) ~= "table" then
				why = "its transformator could not be read"
			else
				for key in pairs(cfg) do
					if string.find(key, "Script$") and not CHAINABLE_HOOKS[key] then why = "its transformator also has " .. key end
				end
				if why == nil and scriptFunction(cfg.updateScript.fileName, file) == nil then
					why = "its transformator's update function was not found"
				end
				for _, hook in ipairs(EMIT_HOOKS) do
					if why == nil and cfg[hook] ~= nil then
						emit = true
						if type(cfg[hook]) ~= "table" or scriptFunction(cfg[hook].fileName, file) == nil then
							why = "its transformator's " .. hook .. " function was not found"
						end
					end
				end
			end
		end
		c = why == nil and { emit = emit } or why
		chainChecks[name] = c
	end
	if type(c) == "table" then return true, c.emit end
	return false, c
end

-- The parts the engine places on the track for a real train, and the axles it
-- turns: a free entity (the run-around's copy) gets neither, so its tender and
-- bogies stay rigid and its small wheels still. Traced live (PROBE, 2026-10-08,
-- an A4 and a Black 5) and in devers' notes: every node that directly holds an
-- axle (the loco body, the tender, a pony truck or bogie) and every fake bogie
-- group is placed by the engine, its centre kept where it is on the vehicle and
-- turned to follow the track under its axles (or its fake bogie positions);
-- axles without an animation of their own (not the driving wheels) are turned
-- as they roll. ghost_real does the same for the copy, from track points the
-- run-around sends. One string per level of detail, as the transformator's
-- parameter runaround_partsN, matched by node count (the order of user
-- transforms: the root 0, then depth first):
--   "n G A  (G times) idx parent x y z yaw  lx ly lz lyaw  px py pz pyaw  a b
--            (A times) idx r sign"
-- (rest pose in the model, rest pose in the parent, the parent's rest pose in
-- the model, the reference points' x in the model; a == b: one point). Only
-- nodes turned about the vertical (or not at all) are included.
local IDENT16 = { 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 }
local function nodeTransf(node)
	local t = type(node.transf) == "table" and node.transf or nil
	if t == nil or #t ~= 16 then return IDENT16 end
	for i = 1, 16 do if type(t[i]) ~= "number" then return IDENT16 end end
	return t
end
-- (x, y, z, yaw) of a column-major 4x4, or nil if it isn't a turn about z
local function poseOf(t)
	local c, s = t[1], t[2]
	if math.abs(t[3]) > 1e-3 or math.abs(t[7]) > 1e-3 or math.abs(t[9]) > 1e-3 or math.abs(t[10]) > 1e-3
		or math.abs(t[11] - 1) > 1e-3 or math.abs(c * c + s * s - 1) > 1e-3 then return nil end
	return { t[13], t[14], t[15], math.atan2 and math.atan2(s, c) or math.atan(s, c) }
end
local function composePose(a, b)
	local c, s = math.cos(a[4]), math.sin(a[4])
	return { a[1] + c * b[1] - s * b[2], a[2] + s * b[1] + c * b[2], a[3] + b[3], a[4] + b[4] }
end
local function lodPartsSpec(root, axleNames, fakes)
	local nodes, byName = {}, {}
	local function walk(node, parent, parentPose)
		local idx = #nodes
		local t = nodeTransf(node)
		local lp = poseOf(t)
		local mp = (lp and parentPose) and composePose(parentPose, lp) or nil
		-- where the node is (also for a scaled one, such as an axle drawn 7% larger)
		local at = parentPose and composePose(parentPose, { t[13], t[14], t[15], math.atan2 and math.atan2(t[2], t[1]) or math.atan(t[2], t[1]) }) or nil
		local rec = { idx = idx, node = node, parent = parent, local_ = lp, model = mp, at = at }
		nodes[#nodes + 1] = rec
		if type(node.name) == "string" then byName[node.name] = rec end
		for _, c in ipairs(type(node.children) == "table" and node.children or {}) do
			if type(c) == "table" then walk(c, rec, mp) end
		end
	end
	walk(root, nil, { 0, 0, 0, 0 })
	local placed, order = {}, {}
	local function place(rec, x)
		if rec == nil or rec.parent == nil or rec.model == nil or rec.local_ == nil or rec.parent.model == nil then return end
		local p = placed[rec.idx]
		if p == nil then
			p = { rec = rec, xs = {} }
			placed[rec.idx] = p
			order[#order + 1] = p
		end
		p.xs[#p.xs + 1] = x
	end
	local axles = {}
	for _, name in ipairs(axleNames or {}) do
		local a = byName[name]
		if a ~= nil and a.at ~= nil then
			place(a.parent, a.at[1])
			if type(a.node.animations) ~= "table" or next(a.node.animations) == nil then
				axles[#axles + 1] = { a.idx, math.min(math.max(a.at[3], 0.3), 1.5), math.cos(a.at[4]) < 0 and -1 or 1 }
			end
		end
	end
	for _, fb in ipairs(fakes or {}) do
		local g = type(fb) == "table" and byName[fb.group] or nil
		if g ~= nil and g.model ~= nil and type(fb.position) == "number" then
			local p = placed[g.idx]
			if p ~= nil and not p.fake then p.xs = {} end -- the fake bogie positions, not its axles
			place(g, g.model[1] + fb.position)
			if placed[g.idx] then placed[g.idx].fake = true end
		end
	end
	table.sort(order, function(u, v) return u.rec.idx < v.rec.idx end)
	local out = { #nodes, #order, #axles }
	for _, p in ipairs(order) do
		local r = p.rec
		local a, b = math.max(table.unpack(p.xs)), math.min(table.unpack(p.xs))
		local par = r.parent
		for _, v in ipairs({ r.idx, par.idx, r.model[1], r.model[2], r.model[3], r.model[4],
			r.local_[1], r.local_[2], r.local_[3], r.local_[4], par.model[1], par.model[2], par.model[3], par.model[4], a, b }) do
			out[#out + 1] = v
		end
	end
	for _, ax in ipairs(axles) do for _, v in ipairs(ax) do out[#out + 1] = v end end
	if #order == 0 and #axles == 0 then return nil end
	local parts = {}
	for i, v in ipairs(out) do parts[i] = (math.floor(v) == v) and tostring(v) or string.format("%.4f", v) end
	return table.concat(parts, " ")
end
-- runaround_partsN strings for a rail vehicle model; {} when there is nothing to place
local function partsSpecs(src)
	local out = {}
	local rv = src.metadata and src.metadata.railVehicle
	local cfg = rv and (rv.config or (type(rv.configs) == "table" and rv.configs[1])) or nil
	if type(cfg) ~= "table" or type(src.lods) ~= "table" then return out end
	local fakes = cfg.fakeBogies
	local flat = type(fakes) == "table" and type(fakes[1]) == "table" and fakes[1].group ~= nil
	for li, lod in ipairs(src.lods) do
		if type(lod) == "table" and type(lod.node) == "table" then
			local f = flat and fakes or (type(fakes) == "table" and fakes[li]) or nil
			local ok, spec = pcall(lodPartsSpec, lod.node, cfg.axles, f)
			if ok and spec ~= nil then out[#out + 1] = spec end
		end
	end
	return out
end
local partsLogged = 0
local function addPartsParams(tc, src, modelName)
	if type(tc) ~= "table" then return end
	local ok, specs = pcall(partsSpecs, src)
	-- (logged for the first steam locos: what the game handed over, and what came of it)
	local snd = src.metadata and src.metadata.soundConfig and src.metadata.soundConfig.soundSet and src.metadata.soundConfig.soundSet.name
	if partsLogged < 12 and type(snd) == "string" and string.find(snd, "steam", 1, true) then
		partsLogged = partsLogged + 1
		local counts = {}
		for _, spec in ipairs(ok and specs or {}) do counts[#counts + 1] = string.match(spec, "^(%d+ %d+ %d+)") end
		local root = type(src.lods) == "table" and type(src.lods[1]) == "table" and src.lods[1].node or nil
		log("loco parts:", tostring(modelName), "- lods:", type(src.lods) == "table" and #src.lods or type(src.lods),
			"first root:", type(root) == "table" and tostring(root.name) or type(root),
			"- specs (nodes placed axles):", ok and (#counts > 0 and table.concat(counts, ", ") or "none") or ("error " .. tostring(specs)))
	end
	if not ok or #specs == 0 then return end
	if type(tc.params) ~= "table" then tc.params = {} end
	for i, spec in ipairs(specs) do tc.params["runaround_parts" .. i] = spec end
	tc.params.runaround_mdl = tc.params.runaround_mdl or modelName
end

-- Points a vehicle with another transformator at the chaining one, keeping the
-- original's name (and any params it already has) for ghost_real to call. False
-- and why when it isn't chained.
local CHAIN_TRF = MOD_ID .. "::/res/models/runaround_ghost/chain.trf"
local CHAIN_EMIT_TRF = MOD_ID .. "::/res/models/runaround_ghost/chain_emit.trf"
local function chainTransformator(md, modelName)
	local tc = md.transformatorConfig
	local name = tc and tc.transformator and tc.transformator.name
	if not CHAIN_TRANSFORMATORS or type(name) ~= "string" or name == "" or string.find(name, "runaround_ghost/", 1, true) then return false, "not chainable" end
	local ok, res = chainable(name, modelName)
	if not ok then return false, res end
	if type(tc.params) ~= "table" then tc.params = {} end
	tc.params.runaround_trf = name
	tc.params.runaround_mdl = modelName
	tc.transformator.name = res and CHAIN_EMIT_TRF or CHAIN_TRF
	return true
end

local stats = { locos = 0, patched = 0, partly = 0, failed = 0, copies = 0, chained = 0 }
local notes = 0
local function note(...)
	notes = notes + 1
	if notes <= 8 then log("loco setup:", ...) end
end

-- Points a loco's own model at the wrappers. Returns whether the loco can be its
-- own ghost (transformator wrapped, and its sound set wrapped or it has none),
-- and whether it can be hidden (its transformator wrapped or chained).
local function patchLoco(modelId, modelName, src)
	local md = src.metadata
	local wrappedTrf = wrappedTransformator(md)
	local soundName = md.soundConfig and md.soundConfig.soundSet and md.soundConfig.soundSet.name
	local wrappedSound = wrappedSoundSet(soundName)
	local trfOk = wrappedTrf ~= nil
	local chained = false
	if trfOk then
		md.transformatorConfig.transformator.name = wrappedTrf
		-- PROBE (temporary): log where the engine puts a steam loco's parts
		if type(soundName) == "string" and string.find(soundName, "steam", 1, true) then
			if type(md.transformatorConfig.params) ~= "table" then md.transformatorConfig.params = {} end
			md.transformatorConfig.params.runaround_probe = true
			md.transformatorConfig.params.runaround_mdl = modelName
		end
	else
		local trf = md.transformatorConfig and md.transformatorConfig.transformator and md.transformatorConfig.transformator.name
		local why
		chained, why = chainTransformator(md, modelName)
		if chained then
			trfOk = true
			if stats.chained < 3 then note(modelName, "has another mod's transformator, chained:", tostring(trf)) end
		else
			note(modelName, "has its own transformator, left alone:", tostring(trf), "-", tostring(why))
		end
	end
	if soundName ~= nil and wrappedSound == nil then note(modelName, "has its own sound set, left alone:", soundName) end
	if not trfOk and wrappedSound == nil then return false end
	if wrappedSound ~= nil then md.soundConfig.soundSet.name = wrappedSound end
	if trfOk then addPartsParams(md.transformatorConfig, src, modelName) end
	local ok, res = pcall(api.res.modelRep.setAsTable, modelId, src)
	if not ok or res == false then
		stats.failed = stats.failed + 1
		note(modelName, "could not be changed:", tostring(res))
		return false
	end
	if chained then stats.chained = stats.chained + 1 end
	local ready = trfOk and (soundName == nil or wrappedSound ~= nil)
	if ready then stats.patched = stats.patched + 1 else stats.partly = stats.partly + 1 end
	return ready, trfOk
end

-- A ghost copy of a loco's model (its meshes via modelPath), or a marker.
local function addGhostModel(name, src, modelName, withEffects)
	if api.res.modelRep.find(name) >= 0 then return true end
	local meta = src.metadata
	local md = {
		transformatorConfig = {
			skipFromLod = -1,
			transformator = { name = wrappedTransformator(meta) or (MOD_ID .. "::/res/models/runaround_ghost/real.trf") },
		},
	}
	if withEffects then addPartsParams(md.transformatorConfig, src, modelName) end
	if withEffects then
		if meta.particleSystem ~= nil then md.particleSystem = clone(meta.particleSystem) end
		local soundName = meta.soundConfig and meta.soundConfig.soundSet and meta.soundConfig.soundSet.name
		local wrapped = wrappedSoundSet(soundName)
		if wrapped ~= nil then md.soundConfig = { soundSet = { name = wrapped } } end
	end
	local ok, res = pcall(api.res.modelRep.addAsTable, name, {
		metadata = md,
		boundingInfo = src.boundingInfo,
		collider = src.collider,
		modelPath = modelName,
	})
	if not ok then note("could not add", name, "-", tostring(res)) end
	return ok
end

mod.postRunFn = function(_configDict, _allModParams)
	-- Under another ID (a mod.io install that renamed it, say) the wrappers' paths
	-- would not resolve, and every patched train would lose its animation and
	-- sound. So then nothing is touched. The train-window card's descriptor
	-- (runaround_vehicle.res.lua) names the mod ID too, and no relative form is
	-- known to work there, so the card will not load either: run-arounds already
	-- in a save still run (with plain ghost copies and the creep), but none can be
	-- set up. The log says so plainly.
	local okId, modId = pcall(getCurrentModId)
	if okId and modId ~= nil and modId ~= MOD_ID then
		log("loco setup: SKIPPED - the mod is loaded as", modId, "but its files name it", MOD_ID,
			"- trains are left untouched, and the run-around card will not appear in the train window",
			"(run-arounds already in a save still run, with plain ghost copies). Please report this.")
		return
	end
	local okAll, all = pcall(api.res.modelRep.getAll, true)
	if not okAll or all == nil then
		log("loco setup: could not list models -", tostring(all))
		return
	end
	-- Every rail vehicle first, to find the file names that are shared.
	local rail, perFile = {}, {}
	for id, name in pairs(all) do
		if type(name) == "string" and not string.find(name, "runaround_", 1, true) then
			local ok, src = pcall(api.res.modelRep.getAsTable, id)
			local file = string.match(name, "([^/]+)%.mdl$")
			if ok and type(src) == "table" and file ~= nil and isRailVehicle(src.metadata) then
				rail[#rail + 1] = { id = id, name = name, file = file, src = src }
				perFile[file] = (perFile[file] or 0) + 1
			end
		end
	end
	local shared = 0
	for _, v in ipairs(rail) do
		stats.locos = stats.locos + 1
		if perFile[v.file] > 1 then
			shared = shared + 1
			note(v.name, "shares its file name with", perFile[v.file] - 1, "other rail vehicle(s): left alone, the run-around uses the generic ghost")
		else
			-- the copy is built from the unchanged metadata, before patching
			if addGhostModel("runaround_ghost_dyn/" .. v.file .. ".mdl", v.src, v.name, true) then
				stats.copies = stats.copies + 1
			end
			local ready, hideable = false, false
			if PATCH_LOCOS then
				local okP, res, trfOk = pcall(patchLoco, v.id, v.name, clone(v.src))
				ready = okP and res == true
				hideable = okP and trfOk == true
				if not okP then note(v.name, "error:", tostring(res)) end
			end
			if ready then addGhostModel("runaround_ghost_real/" .. v.file .. ".mdl", v.src, v.name, false) end
			-- the run-around keeps the loco on the train, hidden: only possible when
			-- its transformator is ours (wrapped or chained)
			if hideable then addGhostModel("runaround_ghost_hide/" .. v.file .. ".mdl", v.src, v.name, false) end
		end
	end
	log(string.format("loco setup: %d rail vehicles; %d can be their own ghost (%d through another mod's transformator), %d partly wrapped, %d could not be changed, %d left alone (file name shared); %d ghost copies built",
		stats.locos, stats.patched, stats.chained, stats.partly, stats.failed, shared, stats.copies))
end

-- A .script.lua file must define data() and return its functions from it
-- (a plain `return mod` fails with "function data() not defined").
function data()
	return mod
end
