-- Load-time script (mod.json postRunScript). Prepares every rail vehicle (locos,
-- coaches and wagons) the game knows about, INCLUDING modded ones, so that the run-around ghost can be drawn
-- from the loco's OWN model with its own sound, smoke, wheels and paint.
--
-- A free entity has no vehicle data, and the game's sound and transformator scripts
-- for locos read vehicle data (the stock sound script dies with "attempt to index
-- local 'vehicleInfo'"). So for each loco:
--
--  * its transformator, when it is the stock train one (default_train.trf), is
--    pointed at res/models/runaround_ghost/real.trf, whose script
--    (res/scripts/ghost_real.script.lua) does exactly what the stock one does for a
--    real train and drives wheels, smoke and paint from the ghost's state for a
--    free entity;
--  * its sound set, when it is one of the game's own, is pointed at the matching
--    copy in res/audio/ghostwrap/: the same sound set with its update script
--    wrapped the same way. (The game refuses sound sets added or changed at run
--    time - soundSetRep.addAsTable / setAsTable throw std::exception - so these
--    copies are shipped as files, generated from the game's own.)
--
-- A loco for which both went through is marked with a marker model,
-- "runaround_ghost_real/<file>.mdl", which the run-around script looks for (a game
-- script cannot read model metadata). For every loco a ghost COPY is also built,
-- "runaround_ghost_dyn/<file>.mdl" (its meshes, particles, the wrapped sound set if
-- there is one, and the wrapped transformator), used when the loco's own model
-- cannot be: e.g. a modded loco with its own sound set or transformator script.
--
-- Markers and copies are named by the model's FILE name, because that is what is
-- known to match between here and the game script (the run-around looks them up
-- by the file name of a train's loco, which works live; whether full model names
-- read the same in both places has not been shown). So a file name that two or
-- more rail vehicles share (two mods' "loco.mdl", say) would be ambiguous: those
-- vehicles are left exactly as they are, with no marker and no copy, and the
-- run-around gives them the generic ghost (and their coaches the creep).
--
-- Everything is wrapped in pcall: a loco the game will not let us change is left
-- exactly as it was.

local mod = {}

-- This mod's ID, as in mod.json. The wrapped transformators and sound sets
-- (res/models/runaround_ghost/*.trf.lua, res/audio/ghostwrap/*.snd.lua) name
-- res/scripts/ghost_real.script with it, the way the game's own DLC names its
-- files: they are plain data files and cannot look the ID up. If the game loads
-- the mod under another ID, nothing is patched (see postRunFn).
local MOD_ID = "runaround_helper_1"
-- false = leave the game's locos untouched (then only the ghost copies are used)
local PATCH_LOCOS = true

-- The game's own sound sets that have a wrapped copy in res/audio/ghostwrap/
-- (generated by the mod's author from the game files; see that folder).
local WRAPPED_SOUND_SETS = {
	["/vehicle/train/shared/sound/cabcar_modern.snd"] = "cabcar_modern",
	["/vehicle/train/shared/sound/train_diesel.snd"] = "train_diesel",
	["/vehicle/train/shared/sound/train_diesel_electric.snd"] = "train_diesel_electric",
	["/vehicle/train/shared/sound/train_diesel_hydraulic.snd"] = "train_diesel_hydraulic",
	["/vehicle/train/shared/sound/train_diesel_old.snd"] = "train_diesel_old",
	["/vehicle/train/shared/sound/train_electric_medium.snd"] = "train_electric_medium",
	["/vehicle/train/shared/sound/train_electric_modern.snd"] = "train_electric_modern",
	["/vehicle/train/shared/sound/train_electric_old.snd"] = "train_electric_old",
	["/vehicle/train/shared/sound/train_steam_modern.snd"] = "train_steam_modern",
	["/vehicle/train/shared/sound/train_steam_old.snd"] = "train_steam_old",
	["/vehicle/waggon/shared/sound/waggon_freight_modern.snd"] = "waggon_freight_modern",
	["/vehicle/waggon/shared/sound/waggon_freight_old.snd"] = "waggon_freight_old",
	["/vehicle/waggon/shared/sound/waggon_modern.snd"] = "waggon_modern",
	["/vehicle/waggon/shared/sound/waggon_old.snd"] = "waggon_old",
	["/vehicle/train/handcar/sound/handcar.snd"] = "handcar",
}

local function log(...)
	local parts = {}
	for i = 1, select("#", ...) do parts[i] = tostring(select(i, ...)) end
	print("[RunAroundHelper] " .. table.concat(parts, " "))
end

local function clone(v)
	if type(v) ~= "table" then return v end
	local o = {}
	for k, x in pairs(v) do o[k] = clone(x) end
	return o
end

-- Any rail vehicle: locos, and (for the ghost rake) coaches and wagons.
local function isRailVehicle(meta)
	local tv = meta and meta.transportVehicle
	return tv ~= nil and tv.carrier == "RAIL" and meta.landVehicle ~= nil
end

-- The wrapped copy of a sound set, as a resource name, or nil if there is none.
local function wrappedSoundSet(soundSetName)
	if type(soundSetName) ~= "string" then return nil end
	local key = soundSetName
	if string.sub(key, 1, 3) == "::/" then key = string.sub(key, 3) end
	local file = WRAPPED_SOUND_SETS[key]
	return file and (MOD_ID .. "::/res/audio/ghostwrap/" .. file .. ".snd") or nil
end

-- The game's stock train transformators and their wrapped versions.
local WRAPPED_TRANSFORMATORS = {
	["default_train.trf"] = "real.trf",
	["tilting_train.trf"] = "real_tilting.trf",
}

-- The wrapped version of a loco's transformator, as a resource name, or nil.
local function wrappedTransformator(meta)
	local name = meta.transformatorConfig and meta.transformatorConfig.transformator and meta.transformatorConfig.transformator.name
	if type(name) ~= "string" then return nil end
	local file = WRAPPED_TRANSFORMATORS[string.match(name, "([^/]+)$") or ""]
	if file == nil or not string.find(name, "vehicle/train/shared/", 1, true) then return nil end
	return MOD_ID .. "::/res/models/runaround_ghost/" .. file
end

local stats = { locos = 0, patched = 0, partly = 0, failed = 0, copies = 0 }
local notes = 0
local function note(...)
	notes = notes + 1
	if notes <= 8 then log("loco setup:", ...) end
end

-- Points a loco's own model at the wrappers. Returns true when the loco can be its
-- own ghost (transformator wrapped, and its sound set wrapped or it has none).
local function patchLoco(modelId, modelName, src)
	local md = src.metadata
	local wrappedTrf = wrappedTransformator(md)
	local soundName = md.soundConfig and md.soundConfig.soundSet and md.soundConfig.soundSet.name
	local wrappedSound = wrappedSoundSet(soundName)
	local trfOk = wrappedTrf ~= nil
	if not trfOk then note(modelName, "has its own transformator, left alone") end
	if soundName ~= nil and wrappedSound == nil then note(modelName, "has its own sound set, left alone:", soundName) end
	if not trfOk and wrappedSound == nil then return false end
	if trfOk then md.transformatorConfig.transformator.name = wrappedTrf end
	if wrappedSound ~= nil then md.soundConfig.soundSet.name = wrappedSound end
	local ok, res = pcall(api.res.modelRep.setAsTable, modelId, src)
	if not ok or res == false then
		stats.failed = stats.failed + 1
		note(modelName, "could not be changed:", tostring(res))
		return false
	end
	local ready = trfOk and (soundName == nil or wrappedSound ~= nil)
	if ready then stats.patched = stats.patched + 1 else stats.partly = stats.partly + 1 end
	return ready
end

-- A ghost copy of a loco's model (its meshes via modelPath), or a marker.
local function addGhostModel(name, src, modelName, withEffects)
	if api.res.modelRep.find(name) >= 0 then return true end
	local meta = src.metadata
	local md = {
		transformatorConfig = {
			skipFromLod = -1,
			transformator = { name = wrappedTransformator(meta) or (MOD_ID .. "::/res/models/runaround_ghost/real.trf") },
		},
	}
	if withEffects then
		if meta.particleSystem ~= nil then md.particleSystem = clone(meta.particleSystem) end
		local soundName = meta.soundConfig and meta.soundConfig.soundSet and meta.soundConfig.soundSet.name
		local wrapped = wrappedSoundSet(soundName)
		if wrapped ~= nil then md.soundConfig = { soundSet = { name = wrapped } } end
	end
	local ok, res = pcall(api.res.modelRep.addAsTable, name, {
		metadata = md,
		boundingInfo = src.boundingInfo,
		collider = src.collider,
		modelPath = modelName,
	})
	if not ok then note("could not add", name, "-", tostring(res)) end
	return ok
end

mod.postRunFn = function(_configDict, _allModParams)
	-- Under another ID (a mod.io install that renamed it, say) the wrappers' paths
	-- would not resolve, and every patched train would lose its animation and
	-- sound. So then nothing is touched: the run-around still works, with the plain
	-- ghost copies shipped in res/models/runaround_ghost/ and the creep.
	local okId, modId = pcall(getCurrentModId)
	if okId and modId ~= nil and modId ~= MOD_ID then
		log("loco setup: SKIPPED - the mod is loaded as", modId, "but its wrapped files name it", MOD_ID,
			"- trains are left untouched; the run-around uses plain ghost copies. Please report this.")
		return
	end
	local okAll, all = pcall(api.res.modelRep.getAll, true)
	if not okAll or all == nil then
		log("loco setup: could not list models -", tostring(all))
		return
	end
	-- Every rail vehicle first, to find the file names that are shared.
	local rail, perFile = {}, {}
	for id, name in pairs(all) do
		if type(name) == "string" and not string.find(name, "runaround_", 1, true) then
			local ok, src = pcall(api.res.modelRep.getAsTable, id)
			local file = string.match(name, "([^/]+)%.mdl$")
			if ok and type(src) == "table" and file ~= nil and isRailVehicle(src.metadata) then
				rail[#rail + 1] = { id = id, name = name, file = file, src = src }
				perFile[file] = (perFile[file] or 0) + 1
			end
		end
	end
	local shared = 0
	for _, v in ipairs(rail) do
		stats.locos = stats.locos + 1
		if perFile[v.file] > 1 then
			shared = shared + 1
			note(v.name, "shares its file name with", perFile[v.file] - 1, "other rail vehicle(s): left alone, the run-around uses the generic ghost")
		else
			-- the copy is built from the unchanged metadata, before patching
			if addGhostModel("runaround_ghost_dyn/" .. v.file .. ".mdl", v.src, v.name, true) then
				stats.copies = stats.copies + 1
			end
			local ready = false
			if PATCH_LOCOS then
				local okP, res = pcall(patchLoco, v.id, v.name, clone(v.src))
				ready = okP and res == true
				if not okP then note(v.name, "error:", tostring(res)) end
			end
			if ready then addGhostModel("runaround_ghost_real/" .. v.file .. ".mdl", v.src, v.name, false) end
		end
	end
	log(string.format("loco setup: %d rail vehicles; %d can be their own ghost, %d partly wrapped, %d could not be changed, %d left alone (file name shared); %d ghost copies built",
		stats.locos, stats.patched, stats.partly, stats.failed, shared, stats.copies))
end

-- A .script.lua file must define data() and return its functions from it
-- (a plain `return mod` fails with "function data() not defined").
function data()
	return mod
end
