-- GENERATED by Runaround Railways from the game's /vehicle/train/handcar/sound/handcar.snd.lua.
-- Identical sound set, with sound file paths made absolute (so they resolve from this
-- mod) and the update script pointed at a wrapper that behaves exactly as the game's for
-- a real train and also works for the run-around ghost (a free entity). Do not edit.
local soundsetutil = require "::/scripts/soundsetutil.lua"

local chuffNames = {
	"::/vehicle/train/handcar/sound/handcar/squeak_1.wav",
	"::/vehicle/train/handcar/sound/handcar/squeak_2.wav",
	"::/vehicle/train/handcar/sound/handcar/squeak_3.wav",
	"::/vehicle/train/handcar/sound/handcar/squeak_4.wav",
	"::/vehicle/train/handcar/sound/handcar/squeak_5.wav",
	"::/vehicle/train/handcar/sound/handcar/squeak_6.wav",
	"::/vehicle/train/handcar/sound/handcar/squeak_7.wav"
}


function data()

local data = soundsetutil.makeSoundSet()

soundsetutil.makeSteamTrain(data, "::/vehicle/train/shared/sound/train_steam_old/idle.wav",
		"::/vehicle/train/handcar/sound/handcar/fast.wav", 25.0, chuffNames, 25.0, 12.0, 1.0)


soundsetutil.addEvent(data, "horn", { "::/vehicle/tram/shared/sound/tram_old/bell2.wav" }, 50.0)

-- Runaround Railways: same sound set, update script wrapped (see res/scripts/ghost_real.script.lua)
data.updateScript.fileName = "runaround_helper_1::/res/scripts/ghost_real.script@sound.updateSoundSet"

return data

end
