-- GENERATED by Run Around Helper from the game's /vehicle/train/shared/sound/train_steam_old.snd.lua.
-- Identical sound set, with sound file paths made absolute (so they resolve from this
-- mod) and the update script pointed at a wrapper that behaves exactly as the game's for
-- a real train and also works for the run-around ghost (a free entity). Do not edit.
local soundsetutil = require "::/scripts/soundsetutil.lua"

local chuffNames = {
	"::/vehicle/train/shared/sound/train_steam_old/chuff_1.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_2.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_3.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_4.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_5.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_6.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_7.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_8.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_9.wav",
	"::/vehicle/train/shared/sound/train_steam_old/chuff_10.wav"
}

local clackNames = {
	"::/vehicle/train/shared/sound/clack/old/part_1.wav",
	"::/vehicle/train/shared/sound/clack/old/part_2.wav",
	"::/vehicle/train/shared/sound/clack/old/part_3.wav",
	"::/vehicle/train/shared/sound/clack/old/part_4.wav",
	"::/vehicle/train/shared/sound/clack/old/part_5.wav",
	"::/vehicle/train/shared/sound/clack/old/part_6.wav",
	"::/vehicle/train/shared/sound/clack/old/part_7.wav",
	"::/vehicle/train/shared/sound/clack/old/part_8.wav",
	"::/vehicle/train/shared/sound/clack/old/part_9.wav",
	"::/vehicle/train/shared/sound/clack/old/part_10.wav"
}

function data()

local data = soundsetutil.makeSoundSet()

soundsetutil.makeSteamTrain(data, "::/vehicle/train/shared/sound/train_steam_old/idle.wav",
		"::/vehicle/train/shared/sound/train_steam_old/fast.wav", 25.0, chuffNames, 15.0, 12.0, 45.0)

soundsetutil.addTrackSqueal(data, "::/vehicle/train/shared/sound/train/wheels_ringing1.wav", 25.0)
soundsetutil.addTrackBrake(data, "::/vehicle/train/shared/sound/train_steam_old/_brakes.wav", 25.0, .5)

soundsetutil.addEventClacks(data, clackNames, 25.0, 10.0 * 1000.0)
soundsetutil.addEvent(data, "horn", { "::/vehicle/train/shared/sound/train_steam_old/horn.wav" }, 50.0)

-- Run Around Helper: same sound set, update script wrapped (see res/scripts/ghost_real.script.lua)
data.updateScript.fileName = "runaround_helper_1::/res/scripts/ghost_real.script@sound.updateSoundSet"

return data

end
