-- GENERATED by Runaround Railways from the game's /vehicle/train/shared/sound/train_diesel_old.snd.lua.
-- Identical sound set, with sound file paths made absolute (so they resolve from this
-- mod) and the update script pointed at a wrapper that behaves exactly as the game's for
-- a real train and also works for the run-around ghost (a free entity). Do not edit.
local soundsetutil = require "::/scripts/soundsetutil.lua"

local clackNames = {
	"::/vehicle/train/shared/sound/clack/modern/part_1.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_2.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_3.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_4.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_5.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_6.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_7.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_8.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_9.wav",
	"::/vehicle/train/shared/sound/clack/modern/part_10.wav"
}

function data()

local data = soundsetutil.makeSoundSet()

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_diesel_old/train_diesel_old_idle.wav", 25.0,
		{ { .0, .5 }, { .4, .8 }, { 1.0, 0.4 } },
		{ { .0, 1.0 }, { 1.0, 1.3 } }, {"vehicle", "speed01"})

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_diesel_old/train_diesel_old_drive.wav", 25.0,
		{ { .0, .1 }, { .2, .3 }, { 1.0, 1.0 } },
		{ { .0, 0.8 }, { 1.0, 1.4 } }, {"vehicle", "speed01"})

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_diesel_old/train_diesel_old_accelerate.wav", 25.0,
		{ { .0, .0 }, { .1, .6 }, { 1.0, 1.2 } },
		{ { .0, 0.9 }, { 1.0, 1.5 } }, {"vehicle", "power01"})

soundsetutil.addTrackSqueal(data, "::/vehicle/train/shared/sound/train/wheels_ringing1.wav", 25.0)
soundsetutil.addTrackBrake(data, "::/vehicle/train/shared/sound/train_electric_modern/_brakes.wav", 25.0, .5)

soundsetutil.addEventClacks(data, clackNames, 25.0, 10.0 * 1000.0)
soundsetutil.addEvent(data, "horn", { "::/vehicle/train/shared/sound/train_diesel/horn_24_Diesel.wav" }, 50.0)

-- Runaround Railways: same sound set, update script wrapped (see res/scripts/ghost_real.script.lua)
data.updateScript.fileName = "runaround_helper_1::/res/scripts/ghost_real.script@sound.updateSoundSet"

return data

end
