-- GENERATED by Runaround Railways from the game's /vehicle/train/shared/sound/train_electric_old.snd.lua.
-- Identical sound set, with sound file paths made absolute (so they resolve from this
-- mod) and the update script pointed at a wrapper that behaves exactly as the game's for
-- a real train and also works for the run-around ghost (a free entity). Do not edit.
local audioutil = require "::/scripts/audioutil.lua"
local soundsetutil = require "::/scripts/soundsetutil.lua"

local clackNames = {
	"::/vehicle/train/shared/sound/clack/old/part_1.wav",
	"::/vehicle/train/shared/sound/clack/old/part_2.wav",
	"::/vehicle/train/shared/sound/clack/old/part_3.wav",
	"::/vehicle/train/shared/sound/clack/old/part_4.wav",
	"::/vehicle/train/shared/sound/clack/old/part_5.wav",
	"::/vehicle/train/shared/sound/clack/old/part_6.wav",
	"::/vehicle/train/shared/sound/clack/old/part_7.wav",
	"::/vehicle/train/shared/sound/clack/old/part_8.wav",
	"::/vehicle/train/shared/sound/clack/old/part_9.wav",
	"::/vehicle/train/shared/sound/clack/old/part_10.wav"
}

function data()

local data = soundsetutil.makeSoundSet()

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_electric_old/train_electric_old_accelerate.wav", 25.0,
		{ { .0, .4 }, {.1, .9}, { .5, .2 } },
		{ { .0, 1.0 }, { .5, 1.7 } }, {"vehicle", "speed01"})

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_electric_old/train_electric_old_drive.wav", 25.0,
		{ { .1, .0 }, { .5, .8 }, { 1.0, 1.0 } },
		{ { .0, 1.0 }, { .5, 1.7 } }, {"vehicle", "speed01"})

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_electric_old/train_electric_old_power.wav", 25.0,
		{ { .1, .0 }, { .2, .3 }, { 1.0, 1.0 } },
		{ { .0, .5 }, { 1.0, 1.5 } }, {"vehicle", "power01"}, {"vehicle", "speed01"})

soundsetutil.addTrackParam01(data, "::/vehicle/train/shared/sound/train_electric_old/train_electric_old_shift.wav", 25.0,
		{ { .0, .0 }, { .05, .9 }, { .1, 1.0}, { .2, .6}, { .25, .0} },
		{ { .0, 1.0 }, { .2, 1.2 } }, {"vehicle", "speed01"})

soundsetutil.addTrackSqueal(data, "::/vehicle/train/shared/sound/train/wheels_ringing1.wav", 25.0)
soundsetutil.addTrackBrake(data, "::/vehicle/train/shared/sound/train_electric_old/_brakes.wav", 25.0, .5)

soundsetutil.addEventClacks(data, clackNames, 25.0, 10.0 * 1000.0)
soundsetutil.addEvent(data, "horn", { "::/vehicle/train/shared/sound/train_electric_old/whistle2.wav" }, 50.0)

-- Runaround Railways: same sound set, update script wrapped (see res/scripts/ghost_real.script.lua)
data.updateScript.fileName = "runaround_helper_1::/res/scripts/ghost_real.script@sound.updateSoundSet"

return data

end
