-- GENERATED by Runaround Railways from the game's /vehicle/waggon/shared/sound/waggon_freight_old.snd.lua.
-- Identical sound set, with sound file paths made absolute (so they resolve from this
-- mod) and the update script pointed at a wrapper that behaves exactly as the game's for
-- a real train and also works for the run-around ghost (a free entity). Do not edit.
local soundsetutil = require "::/scripts/soundsetutil.lua"

local clackNames = {
	"::/vehicle/train/shared/sound/clack/old/part_1.wav",
	"::/vehicle/train/shared/sound/clack/old/part_2.wav",
	"::/vehicle/train/shared/sound/clack/old/part_3.wav",
	"::/vehicle/train/shared/sound/clack/old/part_4.wav",
	"::/vehicle/train/shared/sound/clack/old/part_5.wav",
	"::/vehicle/train/shared/sound/clack/old/part_6.wav",
	"::/vehicle/train/shared/sound/clack/old/part_7.wav",
	"::/vehicle/train/shared/sound/clack/old/part_8.wav",
	"::/vehicle/train/shared/sound/clack/old/part_9.wav",
	"::/vehicle/train/shared/sound/clack/old/part_10.wav"
}

function data()

local data = soundsetutil.makeSoundSet()

soundsetutil.addTrackParam01(data, "::/vehicle/waggon/shared/sound/waggon_freight_old/drive.wav", 20.0,
		{ { .0, .0 }, { 1.0, 1.0 } },
		{ { .0, 1.0 }, { 1.0, 1.15 } }, {"vehicle", "speed01"})

soundsetutil.addTrackSqueal(data, "::/vehicle/train/shared/sound/train/wheels_ringing2.wav", 20.0)
soundsetutil.addTrackBrake(data, "::/vehicle/train/shared/sound/train/brakes.wav", 20.0, 0.5)

soundsetutil.addEventClacks(data, clackNames, 25.0, 10.0 * 1000.0)
soundsetutil.addEvent(data, "openDoors", { "::/vehicle/waggon/shared/sound/waggon_modern/_waggon_modern_opendoor.wav" }, 5.0)
soundsetutil.addEvent(data, "closeDoors", { "::/vehicle/waggon/shared/sound/waggon_modern/_waggon_modern_closedoor.wav" }, 5.0)

-- Runaround Railways: same sound set, update script wrapped (see res/scripts/ghost_real.script.lua)
data.updateScript.fileName = "runaround_helper_1::/res/scripts/ghost_real.script@sound.updateSoundSet"

return data

end
