import json, re, os
# run from a folder holding sndsrc/ (see AGENTS.md); writes into this repo
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
OUT = os.path.join(ROOT, "res", "audio", "ghostwrap")
MOD_ID = json.load(open(os.path.join(ROOT, "mod.json")))["modId"]
WRAP = MOD_ID + "::/res/scripts/ghost_real.script@sound.updateSoundSet"
index = [l.split() for l in open("sndsrc/_index.txt") if l.strip()]
mapping = []
for fname, resdir in index:
    src = open("sndsrc/" + fname).read()
    def fix_str(m):
        q, s = m.group(1), m.group(2)
        if s.endswith(".wav"):
            if s.startswith("::/"): return m.group(0)
            if s.startswith("/"): return q + "::" + s + q
            return q + "::" + resdir + "/" + s + q
        if s.startswith("/scripts/"): return q + "::" + s + q
        return m.group(0)
    body = re.sub(r'(")([^"\n]*)"', fix_str, src)
    # point the update script at the wrapper, just before the final `return data`
    idx = body.rfind("return data")
    assert idx >= 0, fname
    body = body[:idx] + "-- Runaround Railways: same sound set, update script wrapped (see res/scripts/ghost_real.script.lua)\ndata.updateScript.fileName = \"" + WRAP + "\"\n\n" + body[idx:]
    head = ("-- GENERATED by Runaround Railways from the game's " + resdir + "/" + fname + ".\n"
            "-- Identical sound set, with sound file paths made absolute (so they resolve from this\n"
            "-- mod) and the update script pointed at a wrapper that behaves exactly as the game's for\n"
            "-- a real train and also works for the run-around ghost (a free entity). Do not edit.\n")
    open(os.path.join(OUT, fname), "w").write(head + body)
    mapping.append((resdir + "/" + fname[:-len(".lua")], fname[:-len(".snd.lua")]))
for a, b in mapping: print(a, "->", b)
